# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# count = 0

# while count < 30
#   count += 1
#   Value.create(theme: "classic", content: count)
# end

Value.create(theme: "Dinner With The Family", content: "Someone says something awkward")
Value.create(theme: "Dinner With The Family", content: "Politics brought up in conversation")
Value.create(theme: "Dinner With The Family", content: "Swear word uttered")
Value.create(theme: "Dinner With The Family", content: "Food spills")
Value.create(theme: "Dinner With The Family", content: "A drink spills")
Value.create(theme: "Dinner With The Family", content: "Heated argument occurs")
Value.create(theme: "Dinner With The Family", content: "Food is criticized")
Value.create(theme: "Dinner With The Family", content: "Someone uses their phone at the table")
Value.create(theme: "Dinner With The Family", content: "Packed plate of food")
Value.create(theme: "Dinner With The Family", content: "Someone gets up during dinner")
Value.create(theme: "Dinner With The Family", content: "Food is cold when dinner starts")
Value.create(theme: "Dinner With The Family", content: "Someone 'isn't hungry'")
Value.create(theme: "Dinner With The Family", content: "Savage eater spotted in the wild")
Value.create(theme: "Dinner With The Family", content: "Multiple people talking over eachother")
Value.create(theme: "Dinner With The Family", content: "Dog is given food from the table")
Value.create(theme: "Dinner With The Family", content: "Someone plays with their food")
Value.create(theme: "Dinner With The Family", content: "School is brought up in convo")
Value.create(theme: "Dinner With The Family", content: "Work is brought up in convo")
Value.create(theme: "Dinner With The Family", content: "Music is brought up in convo")
Value.create(theme: "Dinner With The Family", content: "Art is brought up in convo")
Value.create(theme: "Dinner With The Family", content: "Moment of complete silence")
Value.create(theme: "Dinner With The Family", content: "Someone is missing when dinner starts")
Value.create(theme: "Dinner With The Family", content: "'Why don't you have a boyfriend/girlfriend")
Value.create(theme: "Dinner With The Family", content: "Inappropriate joke")
Value.create(theme: "Dinner With The Family", content: "Someone refers to tech by the wrong name")
Value.create(theme: "Dinner With The Family", content: "Someone takes a pic")
Value.create(theme: "Dinner With The Family", content: "Overboozing occurs")
Value.create(theme: "Dinner With The Family", content: "Someone is impatient")
Value.create(theme: "Dinner With The Family", content: "Sports are brought up in convo")
Value.create(theme: "Dinner With The Family", content: "Someone tells a story you've heard before")
Value.create(theme: "Dinner With The Family", content: "Someone asks for the food on someone else's plate")
Value.create(theme: "Dinner With The Family", content: "Fighting over food occurs")
Value.create(theme: "Dinner With The Family", content: "Someone falls asleep")

Value.create(theme: "Party Time", content: "Someone passes out")
Value.create(theme: "Party Time", content: "Someone starts puking")
Value.create(theme: "Party Time", content: "A fight starts")
Value.create(theme: "Party Time", content: "Someone starts crying")
Value.create(theme: "Party Time", content: "Public lewdness")
Value.create(theme: "Party Time", content: "An obnoxious drunk appears")
Value.create(theme: "Party Time", content: "Something gets broken")
Value.create(theme: "Party Time", content: "Group karaoke ensues")
Value.create(theme: "Party Time", content: "The drugs come out")
Value.create(theme: "Party Time", content: "Someone does a dated dance move")
Value.create(theme: "Party Time", content: "Someone shouts something")
Value.create(theme: "Party Time", content: "Music is playing but no one is dancing")
Value.create(theme: "Party Time", content: "Someone complains about the food options")
Value.create(theme: "Party Time", content: "Someone complains about the drink options")
Value.create(theme: "Party Time", content: "Something spills")
Value.create(theme: "Party Time", content: "Someone loses something")
Value.create(theme: "Party Time", content: "Someone asks where the bathroom is")
Value.create(theme: "Party Time", content: "Retro/old-school music starts playing")
Value.create(theme: "Party Time", content: "Bathroom is locked")
Value.create(theme: "Party Time", content: "Alcohol or food (or both) runs out")
Value.create(theme: "Party Time", content: "Someone takes a group selfie")
Value.create(theme: "Party Time", content: "Bathroom line")
Value.create(theme: "Party Time", content: "PDA")
Value.create(theme: "Party Time", content: "Someone falls")
Value.create(theme: "Party Time", content: "An overdresser appears")
Value.create(theme: "Party Time", content: "Someone takes their clothes off")
Value.create(theme: "Party Time", content: "Dancing on top of furniture")
Value.create(theme: "Party Time", content: "Cops make a guest appearance")
Value.create(theme: "Party Time", content: "The party games come out")
Value.create(theme: "Party Time", content: "Someone gets hurt")
Value.create(theme: "Party Time", content: "There's a TV on")

Value.create(theme: "Typical Day in the Office", content: "Printer is down")
Value.create(theme: "Typical Day in the Office", content: "It's too hot/cold")
Value.create(theme: "Typical Day in the Office", content: "Someone has a cold and came in anyway")
Value.create(theme: "Typical Day in the Office", content: "Someone brought cookies/cupcakes/cake for everyone")
Value.create(theme: "Typical Day in the Office", content: "Conference. Call.")
Value.create(theme: "Typical Day in the Office", content: "Someone's lunch mysteriously disappears")
Value.create(theme: "Typical Day in the Office", content: "Stinky food in office microwave")
Value.create(theme: "Typical Day in the Office", content: "Someone bitches about work")
Value.create(theme: "Typical Day in the Office", content: "Loud phone ringtone")
Value.create(theme: "Typical Day in the Office", content: "Accidental office-wide email")
Value.create(theme: "Typical Day in the Office", content: "Loud personal call")
Value.create(theme: "Typical Day in the Office", content: "Long meeting drags")
Value.create(theme: "Typical Day in the Office", content: "Boss looking over someone's shoulder")
Value.create(theme: "Typical Day in the Office", content: "Internet is down")
Value.create(theme: "Typical Day in the Office", content: "Somebody gets fired")
Value.create(theme: "Typical Day in the Office", content: "Happy Birthday is sung")
Value.create(theme: "Typical Day in the Office", content: "IT is called")
Value.create(theme: "Typical Day in the Office", content: "Loud typer")
Value.create(theme: "Typical Day in the Office", content: "Elevator Issues")
Value.create(theme: "Typical Day in the Office", content: "Construction noises")
Value.create(theme: "Typical Day in the Office", content: "Asleep on the job")
Value.create(theme: "Typical Day in the Office", content: "Lunch plans are delayed")
Value.create(theme: "Typical Day in the Office", content: "Meeting room is hogged")
Value.create(theme: "Typical Day in the Office", content: "Teambuilding Workshop")
Value.create(theme: "Typical Day in the Office", content: "There are balloons")
Value.create(theme: "Typical Day in the Office", content: "There is a minor injury")
Value.create(theme: "Typical Day in the Office", content: "Flirtation occurs")
Value.create(theme: "Typical Day in the Office", content: "Supplies run out")
Value.create(theme: "Typical Day in the Office", content: "Coffee runs out")
Value.create(theme: "Typical Day in the Office", content: "Slideshow Presentation")
Value.create(theme: "Typical Day in the Office", content: "Loud music")
